### PR TITLE
EZP-31113: AssignSectionToSubtree event is not handled by search and HTTP cache

### PR DESCRIPTION
**Pull request by adamwojs**
| Question           | Answer
| ------------------ | ------------------
| **JIRA issue**     | [EZP-31113](https://jira.ez.no/browse/EZP-31113)
| **Type**           | Bug
| **Target version** | `master`
| **BC breaks**      | no
| **Doc needed**     | no

https://github.com/ezsystems/ezplatform-http-cache/pull/106 for master

**TODO**:
- [X] Implement feature / fix a bug.
- [x] Rebase after merge https://github.com/ezsystems/ezplatform-http-cache/pull/108
- [ ] Implement tests + specs and passing (`$ composer test`)
- [x] Fix new code according to Coding Standards (`$ composer fix-cs`).
- [x] Ask for Code Review.

### CODE REVIEW

**Comment by adamwojs** [comment]
> Just a side note: I believe it's enough to invalidate path-* only but there is a case I'm not aware of, perhaps 🙂

I will check it 😉

**Comment by andrerom** [comment]
> I will check it 😉

I can confirm that unless some views are missing path tagging.

As for parent, any reason why we think parent should be cleared too?
Could make sense, but then it would be to make sure parent view (not siblings) are cleared in case it inlines children listings for instance, but don't add tags for children for some reason (so bug?).

**Comment by micszo** [comment]
Status update. The Solr part works fine on v3. However there are doubts if Varnish (6.1) works correctly with v3 (master, w/o these changes). @webhdx is helping me confirm if it's a configuration issue or if perhaps we have a bug somewhere. I'll let you know when we pinpoint something.

**Comment by micszo** [comment]
Good news! It appears that https://github.com/ezsystems/ezplatform-http-cache/pull/118 resolves the issue I mentioned before. 🎉 So this finally might be unblocked. \cc @webhdx

**Pull request merged**
