### PR TITLE
Fix: AnonymousRequestMatcher doesn't check session name prefix

### PR DESCRIPTION
**Pull request by blankse**
Requires and Description: https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/pull/434

### CODE REVIEW

**Comment by blankse** [comment]
@andrerom I rebased to master to avoid the conflict in the composer.json

**Comment by andrerom** [comment]
Thanks!  And this now requires friendsofsymfony/http-cache-bundle 1.3.13 right?
And will it break without it? (asking as I'm thinking this should be applied to 0.4 also)

**Comment by blankse** [comment]
Yes will break. Because the YML setting doesn't exist before v1.3.13

**Comment by andrerom** [comment]
Tagged: https://github.com/ezsystems/ezplatform-http-cache/releases/tag/v0.5.0-rc4

Thanks @blankse !! :)

**Pull request merged**
